spring:
  application.name: eureka-client-hystrix-turbine
server:
  port: 8031
security.basic.enabled: false
turbine:
  aggregator:
    clusterConfig: default
  appConfig: microservice-consumer-movie , microservice-consumer-movie-feign-fallback
  clusterNameExpression: new String('default')
eureka:
  client:
    service-url:
      defaultZone: http://chhliu:chhliu123456@localhost:8761/eureka