# eureka.client.registerWithEureka ：表示是否将自己注册到Eureka Server，默认为true。由于当前这个应用就是Eureka Server，故而设为false
# eureka.client.fetchRegistry ：表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false。
# eureka.client.serviceUrl.defaultZone ：设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
server:
  port: 8040

spring:
  application:
    name: microservice-gateway-zuul
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://chhliu:chhliu123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    metadata-map:
      zone: ABC      # eureka可以理解的元数据
      lilizhou: BBC  # 不会影响客户端行为
    lease-renewal-interval-in-seconds: 5

zuul:
  routes:
    users:
      path: /myusers/**
      serviceId: microservice-provider-user


#microservice-provider-user:
#  ribbon:
#    listOfServers: http://192.168.1.101:7901,http://192.168.1.101:7900

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
